substitutions:
  name: esphome-linky
  friendly_name: Linky

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

esp8266:
  board: d1_mini
  restore_from_flash: true

# Enable logging
logger:     
  level: INFO   # INFO for less log, put DEBUG to view all the linky's "étiquettes" received  in the logs
  baud_rate: 0   # disable logging via UART, help to avoid numerous crash with ESP_LOGD
  hardware_uart : UART1
  esp8266_store_log_strings_in_flash: False     # recommanded for ESP8266 https://esphome.io/components/sensor/custom.html

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:
  port: 80

http_request:
  useragent: esphome/device
  id: linky_request_id
  verify_ssl: false

uart:
  id: uart_bus
  rx_pin: GPIO13
#  tx_pin: GPI17
  baud_rate: 1200
  parity: EVEN
  data_bits: 7

teleinfo:
  id: esp_teleinfo
  update_interval: 10s
  historical_mode: true

binary_sensor:
  - platform: status
    id: teleinfo_status
    name: "Status"

  - platform: status
    name: "NodeMCU Status"

  - platform: gpio
    pin:
      number: D3
      mode:
        input: true
        pullup: true
    name: "Heures Creuses"

sensor:
  - platform: wifi_signal
    name: "Signal wifi"
    update_interval: 60s
    unit_of_measurement: dB
    accuracy_decimals: 0
    force_update: false
    icon: mdi:wifi

  - platform: template
    name: "Template sensor on client"
    id: template_sensor_id
    
  - platform: uptime
    id: uptime_seconds
    name: "Uptime Sensor"
    update_interval: 60s
    unit_of_measurement: s
    accuracy_decimals: 0
    force_update: false
    icon: mdi:timer
    
  - platform: teleinfo
    tag_name: "IINST"
    name: "Stroom"
    unit_of_measurement: "A"
    icon: mdi:current-ac
    id: "iinst"

  - platform: teleinfo
    tag_name: "URMS1"
    name: "Linky Tension Efficace"
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    icon: mdi:flash-triangle

  - platform: teleinfo
    tag_name: "PAPP"
    name: "Energie"
    device_class: "energy"
    state_class: "total_increasing"
    unit_of_measurement: "VA"
    icon: mdi:flash
    id: "papp"

#  - platform: teleinfo
#    tag_name: "PREF"
#    name: "Energie (ref)"
#    device_class: "energy"
#    state_class: "total"
#    unit_of_measurement: "kVA"
#    icon: mdi:flash

#  - platform: teleinfo
#    tag_name: "HCHC"
#    id: hchc
#    name: "Index HC"
#    unit_of_measurement: "kWh"
#    device_class: "energy"
#    state_class: "total_increasing"
#    accuracy_decimals: 3 
#    filters:
#      - multiply: 0.001
#    icon: mdi:gauge

#  - platform: teleinfo
#    tag_name: "HCHP"
#    id: hchp
#    unit_of_measurement: "kWh"
#    device_class: "energy"
#    state_class: "total_increasing"
#    name: "Index HP"
#    accuracy_decimals: 3 
#    filters:
#      - multiply: 0.001
#    icon: mdi:gauge

#  - platform: teleinfo
#    tag_name: "EJPHN"
#    name: "Index EJP Normal"
#    unit_of_measurement: kWh
#    device_class: "energy"
#    state_class: "total_increasing"
#    accuracy_decimals: 3
#    filters:
#     - multiply: 0.001
  
#  - platform: teleinfo
#    tag_name: "EJPHPM"
#    name: "Index EJP Pointe"
#    unit_of_measurement: kWh
#    device_class: "energy"
#    state_class: "total_increasing"
#    accuracy_decimals: 3
#    filters:
#      - multiply: 0.001

  - platform: teleinfo
    tag_name: "IMAX"
    name: "Intensite max"
    device_class: "energy"
    state_class: "total_increasing"
    unit_of_measurement: "A"
    icon: mdi:current-ac

  - platform: teleinfo
    tag_name: "ISOUSC"
    name: "Intensite souscrite"
    device_class: "energy"
    state_class: "total_increasing"
    unit_of_measurement: "A"
    icon: mdi:current-ac

  - platform: teleinfo
    tag_name: "IINST"
    name: "Intensite"
    device_class: "energy"
    state_class: "total_increasing"
    unit_of_measurement: "A"
    icon: mdi:current-ac

  - platform: teleinfo
    tag_name: "EAIT"
    name: "Energie active injectee totale"
    unit_of_measurement: "Wh"
    icon: mdi:gauge

  - platform: teleinfo
    tag_name: "BBRHCJB"
    name: "Heures Creuses Jours Bleus"
    device_class: "energy"
    state_class: "total_increasing"
    unit_of_measurement: "Wh"
    icon: mdi:gauge
    
  - platform: teleinfo
    tag_name: "BBRHPJB"
    name: "Heures Pleines Jours Bleus"
    device_class: "energy"
    state_class: "total_increasing"
    unit_of_measurement: "Wh"
    icon: mdi:gauge

  - platform: teleinfo
    tag_name: "BBRHCJW"
    name: "Heures Creuses Jours Blancs"
    device_class: "energy"
    state_class: "total_increasing"
    unit_of_measurement: "Wh"
    icon: mdi:gauge

  - platform: teleinfo
    tag_name: "BBRHPJW"
    name: "Heures Pleines Jours Blancs"
    device_class: "energy"
    state_class: "total_increasing"
    unit_of_measurement: "Wh"
    icon: mdi:gauge

  - platform: teleinfo
    tag_name: "BBRHCJR"
    name: "Heures Creuses Jours Rouges"
    device_class: "energy"
    state_class: "total_increasing"
    unit_of_measurement: "Wh"
    icon: mdi:gauge

  - platform: teleinfo
    tag_name: "BBRHPJR"
    name: "Heures Pleines Jours Rouges"
    device_class: "energy"
    state_class: "total_increasing"
    unit_of_measurement: "Wh"
    icon: mdi:gauge

  - platform: teleinfo
    tag_name: "DEMAIN"
    name: "Couleur Demain"
    icon: mdi:handshake

  - platform: teleinfo
    tag_name: "OPTARIF"
    name: "Type abonnement"
    icon: mdi:handshake

  - platform: teleinfo
    tag_name: "LTARF"
    name: "Tarif en cours"
    icon: mdi:handshake

#  - platform: teleinfo
#    tag_name: "NTARF"
#    name: "Index Tarifaire"
#    icon: mdi:handshake

#  - platform: teleinfo
#    tag_name: "HHPHC"
#    name: "Horaire Heures Pleines Heures Creuses"
#    icon: mdi:handshake
  
#  - platform: teleinfo
#    tag_name: "PTEC"
#    name: "Tarif en cours"
#    icon: mdi:clock-time-nine-outline

#  - platform: teleinfo
#    tag_name: "ADPS"
#    name: "Dépassement De Puissance Souscrite"
#    icon: mdi:clock-time-nine-outline

# - platform: teleinfo
#    tag_name: "RELAIS"
#    name: "Relais"

button:
  - platform: restart
    name: "Teleinfo Restart"

text_sensor:
  - platform: teleinfo
    tag_name: "PTEC"
    name: "Tarif actuel"
    icon: mdi:clock-time-nine-outline
    id: "ptec"
